<?xml version="1.0" encoding="utf-8"?><Database Name="db_students" Class="StudentsDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.tbl_student" Member="tbl_students">
    <Type Name="tbl_student">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_student2" Member="tbl_student2s">
    <Type Name="tbl_student2">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>